### ISSUE TITLE
Entity freeze wrecks farms and makes ancient cities a struggle to raid.

### ISSUE THREAD

**Issue by HanosThePlacid** [2mal3/No-Lag#12]
### Minecraft version

23w13a (1.20)

### Datapack version

v3.1.3

### Expected Behavior

It should be possible to increase entity freezing distance to 128 blocks.
Wardens should be exempt from entity freeze.

### Actual Behavior

"Entity freezing ✔
Freezing distance " cannot be inscreased further than 86 blocks.
This breaks all farms that utilise the 128 block mob spawn range

Enitity Freeze also freezes wardens when they should be exempt. Because of this unless the freeze distance is more than 64 blocks they usually do not despawn when you run away but stay there. This caused multiple nightmares while raiding ancient cities as multiple wardens were standing guard around certain areas becoming active again if you get closer then 64 or 42 blocks.

### Reproduction Steps

Mobfarm:
1. Build a mob farm and an afk spot 120 above.
2. Stand on the afk spot for some time. 
3. Check the chests.
4. No fruit.

Warden:
1. Spawn a warden.
2. Run away  and stay away from it by more than 42/64/86 blocks depending on your entity freeze settings. 
3. It will freeze. be invincible to arrows and tridents. And will refuse to despawn.

### Additional information

I love your no lag datapack. Hope you update it soon. Heads up. ヾ(•ω•`)o

**Comment by 2mal3** [comment]
Thank you very much! Finally, a good bug report again.
An update is coming soon.
