### ISSUE TITLE
Named mobs, minecarts with entities in them (probably boats too) and leads get deleted by thee ntity clear

### ISSUE THREAD

**Issue by abitcher** [2mal3/No-Lag#13]
### Minecraft version

1.19.2

### Datapack version

v3.12

### Expected Behavior

They should not be. Those are very important entities

### Actual Behavior

They are. This breaks a whole bunch of stuff

### Reproduction Steps

1. Have those entities existing
2. Wait for next cycle

**Comment by abitcher** [comment]
> The Minecraft and Datpack versions are outdated and no longer supported. Please try the new version of both and if it still doesn't work I may be able to help.
The new version's changelogs say nothing about fixing this

**Comment by 2mal3** [comment]
New versions of Minecraft may introduce or fix bugs that have new effects on datapacks. For example, a bug fix for Minecraft in 23w12a introduced a new bug in the datapack that was not present in 1.19.4.
